global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30031 #for minikube deployment only

cloudProvider:
  dockerRegistryUrl: 10.45.128.61:5000
  imagePullSecretName: pullSecretName
  flavor: minikube

storage:
  accessModes: ReadWriteOnce
  storageSize: 5Gi
  storageClass: azure-file
  pv:
    enabled: false
    hostPath: /raster/gpkgs
  internalPvc:
    enabled: false
    name: internal-pvc
  gpkgsPvc:
    enabled: false
    name: gpkgs-storage

image:
  repository: 10.45.128.61:5000/tiles-imploder
  tag: latest

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  tilesDirectoryPath: "/tilesStorage"
  downloadServerUrl: "http://file-download-server-file-download-server/downloads"
  queue: 
    jobManagerBaseUrl: "http://job-manager-job-manager"
    heartbeatManagerBaseUrl: "http://job-manager-heartbeat-manager"
    dequeueIntervalMs: 1000
    heartbeatIntervalMs: 300
    jobType: "rasterTilesExporter"
    taskType: "rasterTilesExporter"
    expirationDate: 30
  maxAttempts: 3
  geohash: 
    precision: 7
  gpkg:
    path: "/gpkgStorage"
    resampling: "bilinear"
    tilingScheme: "InspireCRS84Quad"
  batchSize: 15
  httpRetry: 
    attempts: 5
    delay: "exponential"
    shouldResetTimeout: true
  
resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  path: /

ingress:
  enabled: false
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
