{{- $chartName := include "tiles-imploder.name" . -}}
{{- $tracingUrl := include "tiles-imploder.tracingUrl" . -}}
{{- $metricsUrl := include "tiles-imploder.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  TILES_DIR_PATH: {{ .Values.env.tilesDirectoryPath | quote }}
  QUEUE_JOB_MANAGER_BASE_URL: {{ .Values.env.queue.jobManagerBaseUrl | quote }}
  QUEUE_HEARTBEAT_MANAGER_BASE_URL: {{ .Values.env.queue.heartbeatManagerBaseUrl | quote }}
  QUEUE_HEARTBEAT_INTERVAL_MS: {{ .Values.env.queue.heartbeatIntervalMs | quote }}
  QUEUE_JOB_TYPE: {{ .Values.env.queue.jobType | quote }}
  QUEUE_TASK_TYPE: {{ .Values.env.queue.taskType | quote }}
  DOWNLOAD_SERVER_URL: {{ .Values.env.downloadServerUrl | quote }}
  MAX_ATTEMPTS: {{ .Values.env.maxAttempts | quote }}
  GEOHASH_PRECISION: {{ .Values.env.geohash.precision | quote}}
  GPKG_PATH: {{ .Values.env.gpkg.path | quote }}
  GPKG_RESAMPLING: {{ .Values.env.gpkg.resampling | quote }}
  GPKG_TILING_SCHEME: {{ .Values.env.gpkg.tilingScheme | quote }}
  BATCH_SIZE: {{ .Values.env.batchSize | quote }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_RESET_TIMEOUT: {{ .Values.env.httpRetry.shouldResetTimeout | quote }}
{{- end }}
