{{- $chartName := include "ts-server-boilerplate.name" . -}}
{{- $tracingUrl := include "ts-server-boilerplate.tracingUrl" . -}}
{{- $metricsUrl := include "ts-server-boilerplate.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  TILES_DIR_PATH: {{ .Values.env.tilesDirectoryPath }}
  QUEUE_JOB_MANAGER_BASE_URL: {{ .Values.env.queue.jobManagerBaseUrl }}
  QUEUE_HEARTBEAT_MANAGER_BASE_URL: {{ .Values.env.queue.heartbeatManagerBaseUrl }}
  QUEUE_HEARTBEAT_INTERVAL_MS: {{ .Values.env.queue.heartbeatIntervalMs }}
  QUEUE_JOB_TYPE: {{ .Values.env.queue.jobType }}
  QUEUE_TASK_TYPE: {{ .Values.env.queue.taskType }}
  DOWNLOAD_SERVER_URL: {{ .Values.env.downloadServerUrl }}
  MAX_ATTEMPTS: {{ .Values.env.maxAttempts }}
  GEOHASH_PRECISION: {{ .Values.env.geohash.precision }}
  GPKG_PATH: {{ .Values.env.gpkg.path }}
  GPKG_RESAMPLING: {{ .Values.env.gpkg.resampling }}
  GPKG_TILING_SCHEME: {{ .Values.env.gpkg.tilingScheme }}
  BATCH_SIZE: {{ .Values.env.batchSize }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay }}
  HTTP_RETRY_RESET_TIMEOUT: {{ .Values.env.httpRetry.shouldResetTimeout }}
{{- end }}
