{{- $releaseName := .Release.Name -}}
{{- $chartName := include "tiles-imploder.name" . -}}
{{- $cloudProviderFlavor := include "tiles-imploder.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "tiles-imploder.cloudProviderDockerRegistryUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "tiles-imploder.environment" . }}
    release: {{ $releaseName }}
    {{- include "tiles-imploder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "tiles-imploder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "tiles-imploder.selectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.cloudProvider.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.cloudProvider.imagePullSecretName | quote }}
    {{- end }}
      volumes:
      - name: internal-storage
        persistentVolumeClaim:
          claimName: {{ .Values.storage.internalPvc.name }} 
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          {{- if ne $cloudProviderFlavor "minikube" }}
          image: {{ $cloudProviderDockerRegistryUrl }}/{{ .repository }}:{{ .tag }}
          {{- else }}
          image: {{ .repository }}:{{ .tag }}
          {{- end }}
          {{- end }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: http
          volumeMounts:
            - name: internal-storage
              mountPath: {{ .Values.env.tilesDirectoryPath }}
              subPath: tiles 
            - name: internal-storage 
              mountPath: {{ .Values.env.gpkg.path }} 
              subPath: gpkgs
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
{{- end -}}
