{{- $releaseName := .Release.Name -}}
{{- $chartName := include "tiles-imploder.name" . -}}
{{- $cloudProviderFlavor := include "tiles-imploder.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "tiles-imploder.cloudProviderDockerRegistryUrl" . -}}
{{- $cloudProviderImagePullSecretName := include "tiles-imploder.cloudProviderImagePullSecretName" . -}}
{{- $volumesNeeded := or (.Values.rasterCommon.storage.fs.internalPvc.enabled) (.Values.intermediateStorage.enabled) }}

{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "tiles-imploder.environment" . }}
    release: {{ $releaseName }}
    {{- include "tiles-imploder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "tiles-imploder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "tiles-imploder.selectorLabels" . | nindent 8 }}
      {{- if .Values.resetOnConfigChange }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}        
    spec:
    {{- if $cloudProviderImagePullSecretName }}
      imagePullSecrets:
        - name: {{ $cloudProviderImagePullSecretName | quote }}
    {{- end }}
    {{- if $volumesNeeded }}
      volumes:
      {{- if .Values.intermediateStorage.enabled }}
      - name: intermediate-storage
        emptyDir:
          sizeLimit: {{ .Values.intermediateStorage.sizeLimit }}
      {{- end }}
      {{- if .Values.rasterCommon.storage.fs.internalPvc.enabled }}
      - name: internal-storage
        persistentVolumeClaim:
          claimName: {{ .Values.rasterCommon.storage.fs.internalPvc.name }}
      - name: gpkgs-storage
        persistentVolumeClaim:
          claimName: {{ .Values.rasterCommon.storage.fs.internalPvc.name }}
      {{- end }}
    {{- end }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          {{- if ne $cloudProviderFlavor "minikube" }}
          image: {{ $cloudProviderDockerRegistryUrl }}/{{ .repository }}:{{ .tag }}
          {{- else }}
          image: {{ .repository }}:{{ .tag }}
          {{- end }}
          {{- end }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: http
          {{- if $volumesNeeded }}              
          volumeMounts:
            {{- if .Values.intermediateStorage.enabled }}
            - name: intermediate-storage
              mountPath: {{ .Values.env.gpkg.intermediatePath }}
            {{- end }}
            {{- if .Values.rasterCommon.storage.fs.internalPvc.enabled }}
            - name: internal-storage
              mountPath: {{ .Values.env.tilesDirectoryPath }}
              subPath: {{ .Values.rasterCommon.storage.fs.internalPvc.tilesSubPath }}
            - name: gpkgs-storage
              mountPath: {{ .Values.env.gpkg.finalPath }}
              subPath: {{ .Values.rasterCommon.storage.fs.internalPvc.gpkgsSubPath }}
            {{- end }}
          {{- end }}
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
{{- end -}}
