global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  flavor: openshift

image:
  repository: ts-server-boilerplate
  tag: 'latest'

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics
  tilesDirectoryPath: "/path/to/tiles"
  downloadServerUrl: "http://localhost:8084/downloads"
  queue: 
    jobManagerBaseUrl: "http://localhost:8082"
    heartbeatManagerBaseUrl: "http://localhost:8083"
    dequeueIntervalMs: 5000
    heartbeatIntervalMs: 5000
    jobType: "rasterTilesExporter"
    taskType: "rasterTilesExporter"
  maxAttempts: 3
  geohash: 
    precision: 7
  gpkg:
    path: "/path/to/gpkg"
    resampling: "bilinear"
    tilingScheme: "InspireCRS84Quad"
  batchSize: 15
  httpRetry: 
    attempts: 5
    delay: "exponential"
    shouldResetTimeout: true
  

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  path: /

ingress:
  enabled: false
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
